name: fusion_etl

services:
  prd:
    environment:
      - DAGSTER_ENV=prd
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - type: volume
        source: prd
        target: /opt/dagster/storage/
    ports:
      - "3000:3000"

volumes:
  prd:
    driver: local
