name: fusion_etl

services:
  prod:
    environment:
      - DAGSTER_ENV=prod
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: prod
        target: /opt/dagster/storage/
    ports:
      - "3000:3000"

volumes:
  prod:
