name: fusion_etl

services:
  prod:
    environment:
      - DAGSTER_ENV=prod
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - type: volume
        source: fusion_etl_prod
        target: /opt/dagster/storage/
    ports:
      - "3000:3000"

volumes:
  fusion_etl_prod:
    external: true
