dbt_core:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: "{{ env_var('ODBC_DRIVER') }}"
      server: "{{ env_var('FUSION_SERVER') }}"
      port: 1433
      database: "{{ env_var('FUSION_DATABASE') }}"
      schema: dbt_dev
      authentication: CLI
      threads: 12
    prd:
      type: sqlserver
      driver: "{{ env_var('ODBC_DRIVER') }}"
      server: "{{ env_var('FUSION_SERVER') }}"
      port: 1433
      database: "{{ env_var('FUSION_DATABASE') }}"
      schema: dbt_prod
      authentication: CLI
      threads: 12
