ERP_MAPPINGS = [
    {
        "name": "bc_budget_targets_23",
        "status": "inactive",
        "source": "bc_budget_targets_23",
        "target": "[erp].[bc_budget_targets_23]",
    },
    {
        "name": "bc_budget_targets_24",
        "status": "active",
        "source": "bc_budget_targets_24",
        "target": "[erp].[bc_budget_targets_24]",
    },
    {
        "name": "gl_account_categories",
        "status": "active",
        "source": "gl_account_categories",
        "target": "[erp].[gl_account_categories]",
    },
    {
        "name": "gl_accounts",
        "status": "active",
        "source": "gl_accounts",
        "target": "[erp].[gl_accounts]",
    },
    {
        "name": "gl_budget_categories",
        "status": "active",
        "source": "gl_budget_categories",
        "target": "[erp].[gl_budget_categories]",
    },
    {
        "name": "gl_cost_centers",
        "status": "active",
        "source": "gl_cost_centers",
        "target": "[erp].[gl_cost_centers]",
    },
    {
        "name": "gl_funds",
        "status": "active",
        "source": "gl_funds",
        "target": "[erp].[gl_funds]",
    },
    {
        "name": "ppm_actual_costs_23",
        "status": "inactive",
        "source": "ppm_actual_costs_23",
        "target": "[erp].[ppm_actual_costs_23]",
    },
    {
        "name": "ppm_actual_costs_24",
        "status": "active",
        "source": "ppm_actual_costs_24",
        "target": "[erp].[ppm_actual_costs_24]",
    },
    {
        "name": "ppm_budget_situations",
        "status": "active",
        "source": "ppm_budget_situations",
        "target": "[erp].[ppm_budget_situations]",
    },
    {
        "name": "ppm_committed_costs_23",
        "status": "inactive",
        "source": "ppm_committed_costs_23",
        "target": "[erp].[ppm_committed_costs_23]",
    },
    {
        "name": "ppm_committed_costs_24",
        "status": "active",
        "source": "ppm_committed_costs_24",
        "target": "[erp].[ppm_committed_costs_24]",
    },
    {
        "name": "ppm_expenditure_categories",
        "status": "active",
        "source": "ppm_expenditure_categories",
        "target": "[erp].[ppm_expenditure_categories]",
    },
    {
        "name": "ppm_organizations",
        "status": "active",
        "source": "ppm_organizations",
        "target": "[erp].[ppm_organizations]",
    },
    {
        "name": "ppm_projects",
        "status": "active",
        "source": "ppm_projects",
        "target": "[erp].[ppm_projects]",
    },
    {
        "name": "ppm_sources",
        "status": "active",
        "source": "ppm_sources",
        "target": "[erp].[ppm_sources]",
    },
    {
        "name": "prc_suppliers",
        "status": "active",
        "source": "prc_suppliers",
        "target": "[erp].[prc_suppliers]",
    },
]
