RDP_MAPPINGS = [
    {
        "name": "_ExecutionLog",
        "type": "table",
        "source": "srv._ExecutionLog",
        "target": "srv._ExecutionLog",
    },
    {
        "name": "ABODBudgetLine",
        "type": "table",
        "source": "srv.ABODBudgetLine",
        "target": "srv.ABODBudgetLine",
    },
    {
        "name": "Account",
        "type": "table",
        "source": "srv.Account",
        "target": "srv.Account",
    },
    {
        "name": "AccountBudgetCategory",
        "type": "table",
        "source": "srv.AccountBudgetCategory",
        "target": "srv.AccountBudgetCategory",
    },
    {
        "name": "AgeGroup",
        "type": "table",
        "source": "srv.AgeGroup",
        "target": "srv.AgeGroup",
    },
    {
        "name": "AnnualStatisticalReport",
        "type": "table",
        "source": "srv.AnnualStatisticalReport",
        "target": "srv.AnnualStatisticalReport",
    },
    {
        "name": "ApportionedBudgetLine",
        "type": "table",
        "source": "srv.ApportionedBudgetLine",
        "target": "srv.ApportionedBudgetLine",
    },
    {
        "name": "ApvdABODBudgetLine",
        "type": "table",
        "source": "srv.ApvdABODBudgetLine",
        "target": "srv.ApvdABODBudgetLine",
    },
    {
        "name": "ApvdApportionedBudgetLine",
        "type": "table",
        "source": "srv.ApvdApportionedBudgetLine",
        "target": "srv.ApvdApportionedBudgetLine",
    },
    {
        "name": "ApvdOPSBudgetLine",
        "type": "table",
        "source": "srv.ApvdOPSBudgetLine",
        "target": "srv.ApvdOPSBudgetLine",
    },
    {
        "name": "ApvdSTAFFOPBudgetLine",
        "type": "table",
        "source": "srv.ApvdSTAFFOPBudgetLine",
        "target": "srv.ApvdSTAFFOPBudgetLine",
    },
    {
        "name": "ARNarrativeConfiguration",
        "type": "table",
        "source": "srv.ARNarrativeConfiguration",
        "target": "srv.ARNarrativeConfiguration",
    },
    {
        "name": "ARNarrativeStrategy",
        "type": "table",
        "source": "srv.ARNarrativeStrategy",
        "target": "srv.ARNarrativeStrategy",
    },
    {
        "name": "ARNarrativeStrategyImpactArea",
        "type": "table",
        "source": "srv.ARNarrativeStrategyImpactArea",
        "target": "srv.ARNarrativeStrategyImpactArea",
    },
    {
        "name": "ARNarrativeStrategyOutcomeArea",
        "type": "table",
        "source": "srv.ARNarrativeStrategyOutcomeArea",
        "target": "srv.ARNarrativeStrategyOutcomeArea",
    },
    {
        "name": "BudgetCategory",
        "type": "table",
        "source": "srv.BudgetCategory",
        "target": "srv.BudgetCategory",
    },
    {
        "name": "ContingencyPlan",
        "type": "table",
        "source": "srv.ContingencyPlan",
        "target": "srv.ContingencyPlan",
    },
    {
        "name": "CoreImpactIndicatorImpactArea",
        "type": "table",
        "source": "srv.CoreImpactIndicatorImpactArea",
        "target": "srv.CoreImpactIndicatorImpactArea",
    },
    {
        "name": "CoreIndicatorActual",
        "type": "table",
        "source": "srv.CoreIndicatorActual",
        "target": "srv.CoreIndicatorActual",
    },
    {
        "name": "CoreIndicatorActualDataLimit",
        "type": "table",
        "source": "srv.CoreIndicatorActualDataLimit",
        "target": "srv.CoreIndicatorActualDataLimit",
    },
    {
        "name": "CoreIndicatorAGDActual",
        "type": "table",
        "source": "srv.CoreIndicatorAGDActual",
        "target": "srv.CoreIndicatorAGDActual",
    },
    {
        "name": "CoreIndicatorAGDBaseline",
        "type": "table",
        "source": "srv.CoreIndicatorAGDBaseline",
        "target": "srv.CoreIndicatorAGDBaseline",
    },
    {
        "name": "CoreIndicatorAGDPopulationType",
        "type": "table",
        "source": "srv.CoreIndicatorAGDPopulationType",
        "target": "srv.CoreIndicatorAGDPopulationType",
    },
    {
        "name": "CoreIndicatorBaseline",
        "type": "table",
        "source": "srv.CoreIndicatorBaseline",
        "target": "srv.CoreIndicatorBaseline",
    },
    {
        "name": "CoreIndicatorBaselineDataLimit",
        "type": "table",
        "source": "srv.CoreIndicatorBaselineDataLimit",
        "target": "srv.CoreIndicatorBaselineDataLimit",
    },
    {
        "name": "CoreIndicatorMetaData",
        "type": "table",
        "source": "srv.CoreIndicatorMetaData",
        "target": "srv.CoreIndicatorMetaData",
    },
    {
        "name": "CoreIndicatorPopulationType",
        "type": "table",
        "source": "srv.CoreIndicatorPopulationType",
        "target": "srv.CoreIndicatorPopulationType",
    },
    {
        "name": "CoreIndicatorPopulationTypeConfiguration",
        "type": "table",
        "source": "srv.CoreIndicatorPopulationTypeConfiguration",
        "target": "srv.CoreIndicatorPopulationTypeConfiguration",
    },
    {
        "name": "CoreIndicatorPopulationTypeYear",
        "type": "table",
        "source": "srv.CoreIndicatorPopulationTypeYear",
        "target": "srv.CoreIndicatorPopulationTypeYear",
    },
    {
        "name": "CoreIndicatorScale",
        "type": "table",
        "source": "srv.CoreIndicatorScale",
        "target": "srv.CoreIndicatorScale",
    },
    {
        "name": "CoreOutcomeIndicatorOutcomeArea",
        "type": "table",
        "source": "srv.CoreOutcomeIndicatorOutcomeArea",
        "target": "srv.CoreOutcomeIndicatorOutcomeArea",
    },
    {
        "name": "CoreOutcomeIndicatorTarget",
        "type": "table",
        "source": "srv.CoreOutcomeIndicatorTarget",
        "target": "srv.CoreOutcomeIndicatorTarget",
    },
    {
        "name": "CostCenter",
        "type": "table",
        "source": "srv.CostCenter",
        "target": "srv.CostCenter",
    },
    {
        "name": "Country",
        "type": "table",
        "source": "srv.Country",
        "target": "srv.Country",
    },
    {
        "name": "CPActivationTrigger",
        "type": "table",
        "source": "srv.CPActivationTrigger",
        "target": "srv.CPActivationTrigger",
    },
    {
        "name": "CPOtherPartnersBudget",
        "type": "table",
        "source": "srv.CPOtherPartnersBudget",
        "target": "srv.CPOtherPartnersBudget",
    },
    {
        "name": "CPPopulationPlanningFigures",
        "type": "table",
        "source": "srv.CPPopulationPlanningFigures",
        "target": "srv.CPPopulationPlanningFigures",
    },
    {
        "name": "CPPreparednessActions",
        "type": "table",
        "source": "srv.CPPreparednessActions",
        "target": "srv.CPPreparednessActions",
    },
    {
        "name": "CPUNHCRBudget",
        "type": "table",
        "source": "srv.CPUNHCRBudget",
        "target": "srv.CPUNHCRBudget",
    },
    {
        "name": "Currency",
        "type": "table",
        "source": "srv.Currency",
        "target": "srv.Currency",
    },
    {
        "name": "EnumerationValue",
        "type": "table",
        "source": "srv.EnumerationValue",
        "target": "srv.EnumerationValue",
    },
    {
        "name": "EPMJobCode",
        "type": "table",
        "source": "srv.EPMJobCode",
        "target": "srv.EPMJobCode",
    },
    {
        "name": "EstimatedStaffCost",
        "type": "table",
        "source": "srv.EstimatedStaffCost",
        "target": "srv.EstimatedStaffCost",
    },
    {
        "name": "ExpenditureOrganisation",
        "type": "table",
        "source": "srv.ExpenditureOrganisation",
        "target": "srv.ExpenditureOrganisation",
    },
    {
        "name": "GPIndicatorMetaData",
        "type": "table",
        "source": "srv.GPIndicatorMetaData",
        "target": "srv.GPIndicatorMetaData",
    },
    {
        "name": "GPIndicatorPopulationTypeConfiguration",
        "type": "table",
        "source": "srv.GPIndicatorPopulationTypeConfiguration",
        "target": "srv.GPIndicatorPopulationTypeConfiguration",
    },
    {
        "name": "GPIndicatorScale",
        "type": "table",
        "source": "srv.GPIndicatorScale",
        "target": "srv.GPIndicatorScale",
    },
    {
        "name": "Grade",
        "type": "table",
        "source": "srv.Grade",
        "target": "srv.Grade",
    },
    {
        "name": "HRJobCode",
        "type": "table",
        "source": "srv.HRJobCode",
        "target": "srv.HRJobCode",
    },
    {
        "name": "HRLocation",
        "type": "table",
        "source": "srv.HRLocation",
        "target": "srv.HRLocation",
    },
    {
        "name": "ImpactArea",
        "type": "table",
        "source": "srv.ImpactArea",
        "target": "srv.ImpactArea",
    },
    {
        "name": "ImpactAreaValidity",
        "type": "table",
        "source": "srv.ImpactAreaValidity",
        "target": "srv.ImpactAreaValidity",
    },
    {
        "name": "ImpactStatement",
        "type": "table",
        "source": "srv.ImpactStatement",
        "target": "srv.ImpactStatement",
    },
    {
        "name": "ImpactStatementValidity",
        "type": "table",
        "source": "srv.ImpactStatementValidity",
        "target": "srv.ImpactStatementValidity",
    },
    {
        "name": "Implementer",
        "type": "table",
        "source": "srv.Implementer",
        "target": "srv.Implementer",
    },
    {
        "name": "ImplementerSite",
        "type": "table",
        "source": "srv.ImplementerSite",
        "target": "srv.ImplementerSite",
    },
    {
        "name": "MappingCostCenter",
        "type": "table",
        "source": "srv.MappingCostCenter",
        "target": "srv.MappingCostCenter",
    },
    {
        "name": "MEActivityEstimatedCost",
        "type": "table",
        "source": "srv.MEActivityEstimatedCost",
        "target": "srv.MEActivityEstimatedCost",
    },
    {
        "name": "MoVCoreIndicatorPopulationType",
        "type": "table",
        "source": "srv.MoVCoreIndicatorPopulationType",
        "target": "srv.MoVCoreIndicatorPopulationType",
    },
    {
        "name": "MoVUDGPIndicatorConfiguration",
        "type": "table",
        "source": "srv.MoVUDGPIndicatorConfiguration",
        "target": "srv.MoVUDGPIndicatorConfiguration",
    },
    {
        "name": "MoVUDGPIndicatorPopulationType",
        "type": "table",
        "source": "srv.MoVUDGPIndicatorPopulationType",
        "target": "srv.MoVUDGPIndicatorPopulationType",
    },
    {
        "name": "NarrativeConfiguration",
        "type": "table",
        "source": "srv.NarrativeConfiguration",
        "target": "srv.NarrativeConfiguration",
    },
    {
        "name": "NarrativeContingencyPlan",
        "type": "table",
        "source": "srv.NarrativeContingencyPlan",
        "target": "srv.NarrativeContingencyPlan",
    },
    {
        "name": "NarrativeCountry",
        "type": "table",
        "source": "srv.NarrativeCountry",
        "target": "srv.NarrativeCountry",
    },
    {
        "name": "NarrativeCountryImpactStatement",
        "type": "table",
        "source": "srv.NarrativeCountryImpactStatement",
        "target": "srv.NarrativeCountryImpactStatement",
    },
    {
        "name": "NarrativeCountryOutcomeStatement",
        "type": "table",
        "source": "srv.NarrativeCountryOutcomeStatement",
        "target": "srv.NarrativeCountryOutcomeStatement",
    },
    {
        "name": "NarrativeCountryOutputStatement",
        "type": "table",
        "source": "srv.NarrativeCountryOutputStatement",
        "target": "srv.NarrativeCountryOutputStatement",
    },
    {
        "name": "NarrativeCountryStrategy",
        "type": "table",
        "source": "srv.NarrativeCountryStrategy",
        "target": "srv.NarrativeCountryStrategy",
    },
    {
        "name": "NarrativeCountryStrategyCoreInd",
        "type": "table",
        "source": "srv.NarrativeCountryStrategyCoreInd",
        "target": "srv.NarrativeCountryStrategyCoreInd",
    },
    {
        "name": "NarrativeImpactStatement",
        "type": "table",
        "source": "srv.NarrativeImpactStatement",
        "target": "srv.NarrativeImpactStatement",
    },
    {
        "name": "NarrativeOutcomeStatement",
        "type": "table",
        "source": "srv.NarrativeOutcomeStatement",
        "target": "srv.NarrativeOutcomeStatement",
    },
    {
        "name": "NarrativeOutputStatement",
        "type": "table",
        "source": "srv.NarrativeOutputStatement",
        "target": "srv.NarrativeOutputStatement",
    },
    {
        "name": "NarrativeStrategy",
        "type": "table",
        "source": "srv.NarrativeStrategy",
        "target": "srv.NarrativeStrategy",
    },
    {
        "name": "NarrativeStrategyPlan",
        "type": "table",
        "source": "srv.NarrativeStrategyPlan",
        "target": "srv.NarrativeStrategyPlan",
    },
    {
        "name": "NarrativeStrategyPlanCoreInd",
        "type": "table",
        "source": "srv.NarrativeStrategyPlanCoreInd",
        "target": "srv.NarrativeStrategyPlanCoreInd",
    },
    {
        "name": "NarrativeUDGPIndicatorConfiguration",
        "type": "table",
        "source": "srv.NarrativeUDGPIndicatorConfiguration",
        "target": "srv.NarrativeUDGPIndicatorConfiguration",
    },
    {
        "name": "Office",
        "type": "table",
        "source": "srv.Office",
        "target": "srv.Office",
    },
    {
        "name": "OfficeHistory",
        "type": "table",
        "source": "srv.OfficeHistory",
        "target": "srv.OfficeHistory",
    },
    {
        "name": "Operation",
        "type": "table",
        "source": "srv.Operation",
        "target": "srv.Operation",
    },
    {
        "name": "OperationalMarker",
        "type": "table",
        "source": "srv.OperationalMarker",
        "target": "srv.OperationalMarker",
    },
    {
        "name": "OperationHistory",
        "type": "table",
        "source": "srv.OperationHistory",
        "target": "srv.OperationHistory",
    },
    {
        "name": "OPSBudgetLine",
        "type": "table",
        "source": "srv.OPSBudgetLine",
        "target": "srv.OPSBudgetLine",
    },
    {
        "name": "OrganizationalMarker",
        "type": "table",
        "source": "srv.OrganizationalMarker",
        "target": "srv.OrganizationalMarker",
    },
    {
        "name": "OutcomeArea",
        "type": "table",
        "source": "srv.OutcomeArea",
        "target": "srv.OutcomeArea",
    },
    {
        "name": "OutcomeAreaValidity",
        "type": "table",
        "source": "srv.OutcomeAreaValidity",
        "target": "srv.OutcomeAreaValidity",
    },
    {
        "name": "OutcomeStatement",
        "type": "table",
        "source": "srv.OutcomeStatement",
        "target": "srv.OutcomeStatement",
    },
    {
        "name": "OutcomeStatementValidity",
        "type": "table",
        "source": "srv.OutcomeStatementValidity",
        "target": "srv.OutcomeStatementValidity",
    },
    {
        "name": "OutputStatement",
        "type": "table",
        "source": "srv.OutputStatement",
        "target": "srv.OutputStatement",
    },
    {
        "name": "OutputStatementOperationalMarker",
        "type": "table",
        "source": "srv.OutputStatementOperationalMarker",
        "target": "srv.OutputStatementOperationalMarker",
    },
    {
        "name": "OutputStatementOrganizationalMarker",
        "type": "table",
        "source": "srv.OutputStatementOrganizationalMarker",
        "target": "srv.OutputStatementOrganizationalMarker",
    },
    {
        "name": "OutputStatementValidity",
        "type": "table",
        "source": "srv.OutputStatementValidity",
        "target": "srv.OutputStatementValidity",
    },
    {
        "name": "Pillar",
        "type": "table",
        "source": "srv.Pillar",
        "target": "srv.Pillar",
    },
    {
        "name": "Plan",
        "type": "table",
        "source": "srv.Plan",
        "target": "srv.Plan",
    },
    {
        "name": "PlanCountry",
        "type": "table",
        "source": "srv.PlanCountry",
        "target": "srv.PlanCountry",
    },
    {
        "name": "PlanValidity",
        "type": "table",
        "source": "srv.PlanValidity",
        "target": "srv.PlanValidity",
    },
    {
        "name": "PopulationPlanningFigures",
        "type": "table",
        "source": "srv.PopulationPlanningFigures",
        "target": "srv.PopulationPlanningFigures",
    },
    {
        "name": "PTGResultsLevel",
        "type": "table",
        "source": "srv.PTGResultsLevel",
        "target": "srv.PTGResultsLevel",
    },
    {
        "name": "RegularPosition",
        "type": "table",
        "source": "srv.RegularPosition",
        "target": "srv.RegularPosition",
    },
    {
        "name": "RegularPositionLine",
        "type": "table",
        "source": "srv.RegularPositionLine",
        "target": "srv.RegularPositionLine",
    },
    {
        "name": "RegularPositionLineAmount",
        "type": "table",
        "source": "srv.RegularPositionLineAmount",
        "target": "srv.RegularPositionLineAmount",
    },
    {
        "name": "Risk",
        "type": "table",
        "source": "srv.Risk",
        "target": "srv.Risk",
    },
    {
        "name": "RiskActive",
        "type": "table",
        "source": "srv.RiskActive",
        "target": "srv.RiskActive",
    },
    {
        "name": "RiskImpact",
        "type": "table",
        "source": "srv.RiskImpact",
        "target": "srv.RiskImpact",
    },
    {
        "name": "RiskLikelihood",
        "type": "table",
        "source": "srv.RiskLikelihood",
        "target": "srv.RiskLikelihood",
    },
    {
        "name": "RiskOutcomeStatement",
        "type": "table",
        "source": "srv.RiskOutcomeStatement",
        "target": "srv.RiskOutcomeStatement",
    },
    {
        "name": "RiskRating",
        "type": "table",
        "source": "srv.RiskRating",
        "target": "srv.RiskRating",
    },
    {
        "name": "RiskSubCategory",
        "type": "table",
        "source": "srv.RiskSubCategory",
        "target": "srv.RiskSubCategory",
    },
    {
        "name": "RiskTreatment",
        "type": "table",
        "source": "srv.RiskTreatment",
        "target": "srv.RiskTreatment",
    },
    {
        "name": "Scenario",
        "type": "table",
        "source": "srv.Scenario",
        "target": "srv.Scenario",
    },
    {
        "name": "Situation",
        "type": "table",
        "source": "srv.Situation",
        "target": "srv.Situation",
    },
    {
        "name": "SpecificPlanningFigures",
        "type": "table",
        "source": "srv.SpecificPlanningFigures",
        "target": "srv.SpecificPlanningFigures",
    },
    {
        "name": "STAFFOPBudgetLine",
        "type": "table",
        "source": "srv.STAFFOPBudgetLine",
        "target": "srv.STAFFOPBudgetLine",
    },
    {
        "name": "Strategy",
        "type": "table",
        "source": "srv.Strategy",
        "target": "srv.Strategy",
    },
    {
        "name": "StrategyValidity",
        "type": "table",
        "source": "srv.StrategyValidity",
        "target": "srv.StrategyValidity",
    },
    {
        "name": "SupervisoryOrganisation",
        "type": "table",
        "source": "srv.SupervisoryOrganisation",
        "target": "srv.SupervisoryOrganisation",
    },
    {
        "name": "TemporaryPosition",
        "type": "table",
        "source": "srv.TemporaryPosition",
        "target": "srv.TemporaryPosition",
    },
    {
        "name": "UDGPImpactIndicatorConfiguration",
        "type": "table",
        "source": "srv.UDGPImpactIndicatorConfiguration",
        "target": "srv.UDGPImpactIndicatorConfiguration",
    },
    {
        "name": "UDGPImpactOutcomeIndicatorAGDBaseline",
        "type": "table",
        "source": "srv.UDGPImpactOutcomeIndicatorAGDBaseline",
        "target": "srv.UDGPImpactOutcomeIndicatorAGDBaseline",
    },
    {
        "name": "UDGPImpactOutcomeIndicatorBaseline",
        "type": "table",
        "source": "srv.UDGPImpactOutcomeIndicatorBaseline",
        "target": "srv.UDGPImpactOutcomeIndicatorBaseline",
    },
    {
        "name": "UDGPImpactOutcomeIndicatorBaselineDataLimit",
        "type": "table",
        "source": "srv.UDGPImpactOutcomeIndicatorBaselineDataLimit",
        "target": "srv.UDGPImpactOutcomeIndicatorBaselineDataLimit",
    },
    {
        "name": "UDGPIndicatorActual",
        "type": "table",
        "source": "srv.UDGPIndicatorActual",
        "target": "srv.UDGPIndicatorActual",
    },
    {
        "name": "UDGPIndicatorActualDataLimit",
        "type": "table",
        "source": "srv.UDGPIndicatorActualDataLimit",
        "target": "srv.UDGPIndicatorActualDataLimit",
    },
    {
        "name": "UDGPIndicatorAGDActual",
        "type": "table",
        "source": "srv.UDGPIndicatorAGDActual",
        "target": "srv.UDGPIndicatorAGDActual",
    },
    {
        "name": "UDGPIndicatorAGDPopulationType",
        "type": "table",
        "source": "srv.UDGPIndicatorAGDPopulationType",
        "target": "srv.UDGPIndicatorAGDPopulationType",
    },
    {
        "name": "UDGPIndicatorConfiguration",
        "type": "table",
        "source": "srv.UDGPIndicatorConfiguration",
        "target": "srv.UDGPIndicatorConfiguration",
    },
    {
        "name": "UDGPIndicatorPopulationType",
        "type": "table",
        "source": "srv.UDGPIndicatorPopulationType",
        "target": "srv.UDGPIndicatorPopulationType",
    },
    {
        "name": "UDGPIndicatorPopulationTypeYear",
        "type": "table",
        "source": "srv.UDGPIndicatorPopulationTypeYear",
        "target": "srv.UDGPIndicatorPopulationTypeYear",
    },
    {
        "name": "UDGPIndicatorScale",
        "type": "table",
        "source": "srv.UDGPIndicatorScale",
        "target": "srv.UDGPIndicatorScale",
    },
    {
        "name": "UDGPOutcomeIndicatorConfiguration",
        "type": "table",
        "source": "srv.UDGPOutcomeIndicatorConfiguration",
        "target": "srv.UDGPOutcomeIndicatorConfiguration",
    },
    {
        "name": "UDGPOutcomeIndicatorTarget",
        "type": "table",
        "source": "srv.UDGPOutcomeIndicatorTarget",
        "target": "srv.UDGPOutcomeIndicatorTarget",
    },
    {
        "name": "UDGPOutputIndicatorConfiguration",
        "type": "table",
        "source": "srv.UDGPOutputIndicatorConfiguration",
        "target": "srv.UDGPOutputIndicatorConfiguration",
    },
    {
        "name": "UDGPOutputIndicatorSubTarget",
        "type": "table",
        "source": "srv.UDGPOutputIndicatorSubTarget",
        "target": "srv.UDGPOutputIndicatorSubTarget",
    },
    {
        "name": "UDGPOutputIndicatorTarget",
        "type": "table",
        "source": "srv.UDGPOutputIndicatorTarget",
        "target": "srv.UDGPOutputIndicatorTarget",
    },
    {
        "name": "UNHCRDate",
        "type": "table",
        "source": "srv.UNHCRDate",
        "target": "srv.UNHCRDate",
    },
]
