name: deploy

on:
  push:
    branches: [ "main" ]

jobs:

  deploy-to-docker:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Stop and remove containers, networks
      run: docker compose down
    - name: Create and start containers
      run: docker compose up --build -d
